# Generated by Django 4.1.3 on 2023-06-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_login_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_picture',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
