# Generated by Django 4.1.3 on 2023-06-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_student_login_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_attendance',
            field=models.IntegerField(default=100),
        ),
    ]
