# Generated by Django 4.1.3 on 2023-06-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_student_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_phone_number',
            field=models.IntegerField(default=9984164481),
        ),
    ]
