# Generated by Django 4.1.3 on 2023-06-16 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_student_student_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_description',
            field=models.TextField(default='', max_length=200),
        ),
    ]
