# Generated by Django 4.1.3 on 2023-06-16 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_student_student_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_description',
            field=models.TextField(max_length=200),
        ),
    ]
