# Generated by Django 4.1.3 on 2023-06-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_alter_student_student_email_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_branch',
            field=models.CharField(choices=[('Computer Science & Engineering', 'Computer Science & Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Electrical & Electronics Engineering', 'Electrical & Electronics Engineering'), ('Electronics and Communications Engineering', 'Electronics and Communications Engineering')], default='Computer Science & Engineering', max_length=100),
        ),
    ]
