# Generated by Django 4.1.3 on 2023-06-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_student_student_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_address',
            field=models.TextField(default='Hawkins Circle, LOS ANGELES, CA 90001-2257, USA', max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_branch',
            field=models.CharField(choices=[('Computer Science & Engineering', 'Computer Science & Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Electrical & Electronics Engineering', 'Electrical & Electronics Engineering'), ('Electronics and Communications Engineering', 'Electronics and Communications Engineering')], max_length=100),
        ),
    ]
