# Generated by Django 4.1.3 on 2023-06-19 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_remove_attendance_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='student_roll_number',
            new_name='student_roll_numbe',
        ),
    ]
