# Generated by Django 4.1.3 on 2023-06-19 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_rename_student_roll_number_attendance_student_roll_numbe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
