# Generated by Django 4.1.3 on 2023-06-19 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='student_roll_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
    ]
