# Generated by Django 4.1.3 on 2023-06-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0023_remove_attendance_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('student_roll_number', 'attendance_date'), name='unique_student_attendance'),
        ),
    ]
