# Generated by Django 4.1.3 on 2023-06-19 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0024_attendance_attendance_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
