# Generated by Django 4.1.3 on 2023-06-19 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0026_attendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
