# Generated by Django 4.1.3 on 2023-06-19 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0028_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='attendance_date',
        ),
    ]
