# Generated by Django 4.1.3 on 2023-06-21 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0029_remove_attendance_attendance_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_login_status',
        ),
    ]
