# Generated by Django 4.1.3 on 2023-06-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0030_remove_student_student_login_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='april_attendance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='august_attendance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='december_attendance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='febraury_attendance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='january_attendance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='july_attendance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='june_attendance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='march_attendance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='may_attendance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='november_attendance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='october_attendance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='september_attendance',
            field=models.IntegerField(),
        ),
    ]
