# Generated by Django 4.1.3 on 2023-06-22 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0034_remove_attendance_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='student_roll_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
