# Generated by Django 4.1.3 on 2023-06-22 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0035_alter_attendance_student_roll_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_password',
        ),
    ]
