# Generated by Django 4.1.3 on 2023-06-22 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0036_remove_student_student_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
