# Generated by Django 4.1.3 on 2023-06-22 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0037_delete_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('january_attendance', models.IntegerField()),
                ('febraury_attendance', models.IntegerField()),
                ('march_attendance', models.IntegerField()),
                ('april_attendance', models.IntegerField()),
                ('may_attendance', models.IntegerField()),
                ('june_attendance', models.IntegerField()),
                ('july_attendance', models.IntegerField()),
                ('august_attendance', models.IntegerField()),
                ('september_attendance', models.IntegerField()),
                ('october_attendance', models.IntegerField()),
                ('november_attendance', models.IntegerField()),
                ('december_attendance', models.IntegerField()),
                ('student_roll_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
