# Generated by Django 4.1.3 on 2023-06-23 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0038_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('subject', models.TextField(max_length=150)),
                ('message', models.TextField(max_length=300)),
                ('student_roll_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
