# Generated by Django 4.1.3 on 2023-06-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0039_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
