# Generated by Django 4.1.3 on 2023-06-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0040_alter_contactus_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='student_roll_number',
            field=models.TextField(max_length=150),
        ),
    ]
