# Generated by Django 4.1.3 on 2023-06-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0041_alter_contactus_student_roll_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_branch',
            field=models.CharField(choices=[('CSE', 'Computer Science & Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Electrical & Electronics Engineering', 'Electrical & Electronics Engineering'), ('Electronics and Communications Engineering', 'Electronics and Communications Engineering')], max_length=100),
        ),
    ]
