# Generated by Django 4.1.3 on 2023-06-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0043_alter_student_student_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_branch',
            field=models.CharField(choices=[('Computer Science & Engineering', 'CSE'), ('Mechanical Engineering', 'Mech'), ('Civil Engineering', 'Civil'), ('Electrical & Electronics Engineering', 'EEE'), ('Electronics and Communications Engineering', 'ECE')], max_length=100),
        ),
    ]
