# Generated by Django 4.1.3 on 2023-06-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0044_alter_student_student_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_branch',
            field=models.CharField(choices=[('Computer Science & Engineering', 'Computer Science & Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Electrical & Electronics Engineering', 'Electrical & Electronics Engineering'), ('Electronics and Communications Engineering', 'Electronics and Communications Engineering')], max_length=100),
        ),
    ]
