# Generated by Django 4.1.3 on 2023-06-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0045_alter_student_student_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
    ]
