# Generated by Django 4.1.3 on 2023-06-24 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0046_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_semester',
        ),
        migrations.CreateModel(
            name='BranchSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.branch')),
            ],
        ),
    ]
