# Generated by Django 4.1.3 on 2023-06-24 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0047_remove_student_student_semester_branchsubjects'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BranchSubjects',
        ),
    ]
