# Generated by Django 4.1.3 on 2023-06-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0050_alter_branchsubjects_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchsubjects',
            name='subject_1',
            field=models.TextField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='branchsubjects',
            name='subject_2',
            field=models.TextField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='branchsubjects',
            name='subject_3',
            field=models.TextField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='branchsubjects',
            name='subject_4',
            field=models.TextField(max_length=50, unique=True),
        ),
    ]
