# Generated by Django 4.1.3 on 2023-06-24 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0052_alter_branchsubjects_unique_together_studentmarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmarks',
            old_name='subject1',
            new_name='subject_1',
        ),
        migrations.RenameField(
            model_name='studentmarks',
            old_name='subject2',
            new_name='subject_2',
        ),
        migrations.RenameField(
            model_name='studentmarks',
            old_name='subject3',
            new_name='subject_3',
        ),
        migrations.RenameField(
            model_name='studentmarks',
            old_name='subject4',
            new_name='subject_4',
        ),
    ]
