# Generated by Django 4.1.3 on 2023-06-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0055_alter_studentmarks_subject_1_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchdetails',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
    ]
