# Generated by Django 4.1.3 on 2023-06-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0058_alter_branchdetails_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchdetails',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterUniqueTogether(
            name='branchdetails',
            unique_together={('branch', 'description')},
        ),
    ]
