# Generated by Django 4.1.3 on 2023-06-26 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0061_alter_branchdetails_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='branchdetails',
            unique_together={('branch', 'id')},
        ),
    ]
