# Generated by Django 4.1.3 on 2023-06-26 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0062_alter_branchdetails_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('id', 'student_roll_number')},
        ),
    ]
