# Generated by Django 4.1.3 on 2023-06-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0064_branchdetails_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchdetails',
            name='points',
            field=models.TextField(),
        ),
    ]
