# Generated by Django 4.1.3 on 2023-06-28 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0065_alter_branchdetails_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_email_address',
        ),
    ]
